{{- $appname := printf "%s-%s" .Release.Name .Chart.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appname }}-config
  labels:
    app: {{ $appname }}
data:
  message: {{ .Values.config.message | quote }}
  port: {{ .Values.config.port | quote }}
