{{- $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-config
  labels:
    app: {{ $fullname }}
data:
  MESSAGE: {{ .Values.config.message | quote }}
  PORT: {{ .Values.config.port | quote }}

