{{- $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-config
  labels:
    app: {{ $fullname }}
data:
  dummy: "will be used in Part 5"
