{{- $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 50 | trimSuffix "-" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullname }}-cron
  labels:
    app: {{ $fullname }}-cron
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $fullname }}-cron
        spec:
          restartPolicy: Never
          containers:
            - name: cron-echo
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - "-text=CronJob tick from Helm"
