{{- $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 55 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullname }}-ds
  labels:
    app: {{ $fullname }}-ds
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}-ds
  template:
    metadata:
      labels:
        app: {{ $fullname }}-ds
    spec:
      containers:
        - name: http-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text=DaemonSet says hello from node"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
