{{- $appname := printf "%s-%s" .Release.Name .Chart.Name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appname }}
  labels:
    app: {{ $appname }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ $appname }}
  template:
    metadata:
      labels:
        app: {{ $appname }}
    spec:
      containers:
        - name: {{ $appname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
{{- range .Values.image.command }}
            - {{ . | quote }}
{{- end }}
          ports:
            - containerPort: {{ .Values.service.port | default 5678 }}
