{{- $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 55 | trimSuffix "-" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullname }}-job
  labels:
    app: {{ $fullname }}-job
spec:
  template:
    metadata:
      labels:
        app: {{ $fullname }}-job
    spec:
      restartPolicy: Never
      containers:
        - name: job-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text=Job run from Helm"
