{{- $appname := printf "%s-%s" .Release.Name .Chart.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appname }}-secret
  labels:
    app: {{ $appname }}
type: Opaque
data:
  apiToken: {{ .Values.secret.apiToken | b64enc | quote }}
